### ISSUE TITLE
Setting H265_TRANSCODE doesn't do anything

### ISSUE THREAD

**Issue by teckel12** [Vilsol/Transcoder#7]
Looking at the Python script, H265_TRANSCODE isn't tied to anything, so it's being totally ignored.  I have it set to `H265_TRANSCODE=False`, but it's still transcoding H265 compressed files.  Of course, it's transcoding again as the setting isn't referenced in the code at all.

**Comment by Vilsol** [comment]
This service has been discontinued in favor of the new one here: https://github.com/Vilsol/transcoder-go

Please use that and if you have any more issues, post on that repository.
